project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - cv/cv.qmd
    - blog/index.qmd

website:
  title: "Felipe Dias"
  description: ""
  search: true
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: CV
        href: cv/cv.qmd      
      - text: Blog
        href: blog/index.qmd
  page-footer:
    left: ""
    right: ""


format:
  html:
    include-after-body: goatcounter.html
    code-copy: true
    html-math-method: katex
    allow-html: true
    theme: flatly
    smooth-scroll: true
    lang: en
    css:
      - https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css
      - https://cdnjs.cloudflare.com/ajax/libs/academicons/1.9.6/css/academicons.min.css

execute:
  freeze: auto
  echo: true
  warning: false
